swagger: '2.0'
info:
  version: 0.1.0
  title: brand
  description: Learners Guild Brand
  termsOfService: 'https://www.learnersguild.org/privacypolicy.html'
  contact:
    name: Jeffrey Wescott
    email: jeffrey@learnersguild.org
  license:
    name: ISC
consumes:
  - application/json
produces:
  - application/json
paths:
  /icontags:
    get:
      description: Returns the HTML icons metadata response
      x-swagger-router-controller: IconTags
      operationId: getHTMLMetadataTags
      produces:
        - application/json
      responses:
        '200':
          description: HTML icons metadata response
          schema:
            type: array
            items:
              type: string
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/errorModel'
definitions:
  errorModel:
    type: object
    description: Error information returned by an unsuccessful API call.
    required:
      - code
      - message
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string
